### PR TITLE
MER: bluez: handle URL service record attributes. Fixes MER#1228

### PR DESCRIPTION
**Pull request by hmallat**
Added functionality for handling URL values in service records.

### CODE REVIEW

**Comment by rburchell** [comment]
https://bugs.merproject.org/show_bug.cgi?id=1128 -- are you sure this bug reference is right?

**Comment by hmallat** [comment]
should be 1228, I'll fix the message

**Comment by rburchell** [comment]
Upstream review:

https://codereview.qt-project.org/#/c/123811/

**Comment by hmallat** [comment]
As upstream had already done an equivalent change post 5.2, cherry-picked the commit from there and replaced the local change with that.

**Pull request merged**
